### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by tchap** [mgedmin/profilehooks#14]
I am getting the following error when using `profilehooks`:

```
*** PROFILER RESULTS ***
get_stream_data (/src/services/public_api/public_api/handlers/streams.py:109)
function called 2 times

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/venvs/public_api/lib/python3.6/site-packages/profilehooks.py", line 392, in atexit
    self.print_stats()
  File "/venvs/public_api/lib/python3.6/site-packages/profilehooks.py", line 376, in print_stats
    stats.print_stats(self.entries)
  File "/usr/local/lib/python3.6/pstats.py", line 336, in print_stats
    print(indent, self.total_calls, "function calls", end=' ', file=self.stream)
  File "/venvs/public_api/lib/python3.6/site-packages/_pytest/capture.py", line 231, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
```

Basically I just imported `profile` and decorated a single function. It is a request handler and it is running during tests in a Docker container.

**Comment by mgedmin** [comment]
Apologies for the late response -- new baby in the house, things are a bit hectic.

It looks as if sys.stdout is closed during program shutdown.  The _pytest bit in the traceback is especially interesting.  I'll have to experiment and see how profilehooks can coexist with py.test.

**Comment by mgedmin** [comment]
I can reproduce:
```python
# test.py
import profilehooks


@profilehooks.profile()
def dostuff(x, y):
    return x + y


def test_dostuff():
    assert dostuff(2, 3) == 5
```

```
$ py.test test.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/mg/tmp/pytest-and-profilehooks, inifile: 
plugins: xdist-1.15.0, catchlog-1.2.2
collected 1 items 

test.py .

=========================== 1 passed in 0.01 seconds ===========================

*** PROFILER RESULTS ***
dostuff (/home/mg/tmp/pytest-and-profilehooks/test.py:4)
function called 1 times

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/profilehooks.py", line 392, in atexit
    self.print_stats()
  File "/home/mg/.venv/local/lib/python2.7/site-packages/profilehooks.py", line 376, in print_stats
    stats.print_stats(self.entries)
  File "/usr/lib/python2.7/pstats.py", line 351, in print_stats
    print >> self.stream, indent, self.total_calls, "function calls",
  File "/home/mg/.venv/local/lib/python2.7/site-packages/_pytest/capture.py", line 244, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/profilehooks.py", line 392, in atexit
    self.print_stats()
  File "/home/mg/.venv/local/lib/python2.7/site-packages/profilehooks.py", line 376, in print_stats
    stats.print_stats(self.entries)
  File "/usr/lib/python2.7/pstats.py", line 351, in print_stats
    print >> self.stream, indent, self.total_calls, "function calls",
  File "/home/mg/.venv/local/lib/python2.7/site-packages/_pytest/capture.py", line 244, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
```

I don't know if there's anything `profilehooks` can do to avoid this.

**Comment by mgedmin** [comment]
I've double-checked, and profilehooks isn't stashing any stale `sys.stdout` values anywhere -- my atexit function simply invokes `print("...")`.

This to me looks like a bug in py.test.  Would you care to [file it there](https://github.com/pytest-dev/pytest/issues)?

**Comment by matthiasha** [comment]
This can be worked around by disabling Pytest's stdout capture: `pytest -s`
