### ISSUE TITLE
Tests fail under Python 3.11

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/profilehooks#30]
Two tests fail under 3.11.0rc2+

```
======================================================================
FAIL: test_coverage (__main__.TestCoverage.test_coverage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/profilehooks/test_profilehooks.py", line 111, in test_coverage
    self.assertMultiLineEqual(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '\n**[109 chars]s\n\n>>>>>>     def sample_fn(self, x, y, z):\[244 chars]d.\n' != '\n**[109 chars]s\n\n           def sample_fn(self, x, y, z):\[244 chars]d.\n'
  
  *** COVERAGE RESULTS ***
  sample_fn (/home/mg/src/profilehooks/test_profilehooks.py:84)
  function called 2 times
  
- >>>>>>     def sample_fn(self, x, y, z):
? ^^^^^^
+            def sample_fn(self, x, y, z):
? ^^^^^^
      2:         if x == y == z:
      1:             return "%s" % (x, )
      1:         elif x == y:
  >>>>>>             return "%s %s" % (x, z)
                 else:
      1:             return "%s %s %s" % (x, y, z)
  
- 2 lines were not executed.
? ^
+ 1 lines were not executed.
? ^


======================================================================
FAIL: test_coverage_again (__main__.TestCoverage.test_coverage_again)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/profilehooks/test_profilehooks.py", line 135, in test_coverage_again
    self.assertMultiLineEqual(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "\n**[111 chars]s\n\n>>>>>>     def sample_fn_2(self):\n    1:[157 chars]d.\n" != "\n**[111 chars]s\n\n           def sample_fn_2(self):\n    1:[129 chars]\n\n"
  
  *** COVERAGE RESULTS ***
  sample_fn_2 (/home/mg/src/profilehooks/test_profilehooks.py:92)
  function called 1 times
  
- >>>>>>     def sample_fn_2(self):
? ^^^^^^
+            def sample_fn_2(self):
? ^^^^^^
      1:         try:
      1:             os.path.join('a', 'b')
                 finally:
      1:             x = 5
      1:         del x
  
- 1 lines were not executed.


----------------------------------------------------------------------
```

**Comment by mgedmin** [comment]
So,  Python 3.11 adds a new bytecode at the beginning of the code object, with the line number attributed to the `def`:

```
(Pdb) import dis
(Pdb) !dis.dis(self.fn)
 84           0 RESUME                   0

 85           2 LOAD_FAST                1 (x)
              4 LOAD_FAST                2 (y)
              6 SWAP                     2
              8 COPY                     2
             10 COMPARE_OP               2 (==)
...
```

trace.py never sees evidence of that opcode getting executed, so it ends up being marked as `>>>>>>`.
